### ISSUE TITLE
Stuck on "Probing Audio File"

### ISSUE THREAD

**Issue by gsalkin** [nypublicradio/audiogram#101]
I've recently reconstructed a Ubuntu server to run audiogram using the guideline presented [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04) but now it is stuck on "Probing Audio File".

Here's the error it throws:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffprobe ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Not sure what the issue is based on this. Any ideas? Thanks!

**Comment by ortegeek** [comment]
I have got the same problem, i totally reinstall Node.js with this link : [full installation instructions](https://github.com/nypublicradio/audiogram/blob/master/INSTALL.md)
Now, it work.
