### ISSUE TITLE
Fixed issue with install, now stuck in queue

### ISSUE THREAD

**Issue by hank3rd** [nypublicradio/audiogram#110]
I get most of the way through the install, but I am receiving a permission issue?

Here is the reply in terminal and attaching log:

34 warnings and 7 errors generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hhoffmeier/Audiogram/audiogram/node_modules/canvas
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

[log.txt](https://github.com/nypublicradio/audiogram/files/2652994/log.txt)

**Comment by hank3rd** [comment]
I fixed this issue with this fix: https://github.com/nypublicradio/audiogram/issues/104

But now I am getting a message "waiting for other jobs to finish, #1 in queue". Any ideas

I have tried removing any files in tmp and media
