### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by mikeymaff** [nypublicradio/audiogram#30]
I have this running properly on localhost:8888, I can use the tool, but when I hit "Generate", I get this error in the browser (in html under the loading gif):

`{"status":"error","numFrames":285,"error":{"code":"EACCES","errno":"EACCES","syscall":"spawn"}}`

and I get this error in my console:

`/Users/michaelmaffattone/Documents/Dev/audiogram-generator/audiogram/bin/worker:40
      throw err;
      ^

Error: spawn EACCES
    at exports._errnoException (util.js:1008:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:372:9)
    at exports.execFile (child_process.js:139:15)
    at module.exports (/Users/michaelmaffattone/Documents/Dev/audiogram-generator/audiogram/node_modules/waveform/index.js:29:3)
    at getWaveform (/Users/michaelmaffattone/Documents/Dev/audiogram-generator/audiogram/audiogram/waveform.js:17:3)
    at Audiogram.getWaveform (/Users/michaelmaffattone/Documents/Dev/audiogram-generator/audiogram/audiogram/index.js:64:3)
    at start (/Users/michaelmaffattone/Documents/Dev/audiogram-generator/audiogram/node_modules/d3-queue/build/d3-queue.js:67:13)
    at poke (/Users/michaelmaffattone/Documents/Dev/audiogram-generator/audiogram/node_modules/d3-queue/build/d3-queue.js:55:26)
    at /Users/michaelmaffattone/Documents/Dev/audiogram-generator/audiogram/node_modules/d3-queue/build/d3-queue.js:83:25`

Any ideas?

**Comment by veltman** [comment]
This is probably a file permissions error.  I'm guess you will also get an error if you run:

```
/Users/michaelmaffattone/Documents/Dev/audiogram-generator/audiogram/node_modules/waveform/build/Release/waveform
```

One possible solution is to make sure you have executable privileges on the file:

```
sudo chmod go+x /Users/michaelmaffattone/Documents/Dev/audiogram-generator/audiogram/node_modules/waveform/build/Release/waveform
```

But you might run into a similar error later, in which case, rinse/repeat.

You may also need to ensure you own all of the Audiogram files:

```
sudo chown -R `whoami` /Users/michaelmaffattone/Documents/Dev/audiogram-generator/
```

**Comment by mikeymaff** [comment]
@veltman - thank you. Saw this this morning and I've been working on trying to get this to work all day, still no luck though. I believe all my permissions are correct.

It seems like the issue is that when the audio file is generated in 
`audiogram/tmp/23f33470-5a7a-11e6-bf6d-f3329f438b47/audio`
that new file doesn't have the proper permissions.

Here's what I see when I `ls -al` on the directory:

`-rw-r--r--   1 michaelmaffattone  staff  6431600 Aug  4 15:27 audio
-rw-r--r--   1 michaelmaffattone  staff   121865 Aug  4 15:27 audio-trimmed.mp3`

**Comment by mikeymaff** [comment]
Still not sure why this was broken, but I was able to get the application working by just going through the installation instructions in a new directory.

**Comment by veltman** [comment]
Were there any strange characters or spaces in the old folder name, by any chance?
