### ISSUE TITLE
unkown error

### ISSUE THREAD

**Issue by mobiuscoffee** [nypublicradio/audiogram#40]
Fairly often an audiogram will fail to finish creating because of an "unkown error". The docker console gives this out:

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/home/audiogram/audiogram/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/home/audiogram/audiogram/node_modules/express/lib/response.js:164:12)
    at module.exports (/home/audiogram/audiogram/server/error.js:17:9)
    at Layer.handle_error (/home/audiogram/audiogram/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/audiogram/audiogram/node_modules/express/lib/router/index.js:310:13)
    at /home/audiogram/audiogram/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/audiogram/audiogram/node_modules/express/lib/router/index.js:330:12)
    at next (/home/audiogram/audiogram/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/home/audiogram/audiogram/node_modules/express/lib/router/layer.js:67:12)
```

**Comment by veltman** [comment]
Is there a specific sequence of events that reliably produces this error?

**Comment by mobiuscoffee** [comment]
Not 100% reliable, but it seems to happen more often if the window/tab loses focus. It's hard to confirm though since I'm not monitoring it if it doesn't have focus.

**Comment by veltman** [comment]
Will close this for now, but if you can give me a sequence and configuration that always produces the error I'll investigate.

**Comment by veltman** [comment]
I think I know what caused this.  If an error occurred while checking the status of a pending job, it would send an error response and then throw an error, which trickled down to an Express error handler trying to re-send headers.  The most likely underlying error was a corrupted file or something - I've fixed this on the `refactor` branch so that you'll at least get a message describing the real error.

**Comment by mobiuscoffee** [comment]
I've had another chance to play around with audiograms and I have a reliable way to create an `unkown error`

Anytime a process is Not Responding the audiogram stops processing and gives an `unknown error`

**Comment by dahngeek** [comment]
I have the same problem but it happens each time I want to render an audiogram, always.

It goes like Rendering frames 4%, 6%, 10%.. and bam! "uknown error"

**Comment by DanielFrankDK** [comment]
I have the same problem. Any updates?

`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at load (/home/pi/audiogram/lib/transports/redis/fake.js:14:15)
    at getJobList (/home/pi/audiogram/lib/transports/redis/fake.js:65:19)
    at start (/home/pi/audiogram/node_modules/d3-queue/build/d3-queue.js:74:11)
    at poke (/home/pi/audiogram/node_modules/d3-queue/build/d3-queue.js:58:11)
    at Queue.defer (/home/pi/audiogram/node_modules/d3-queue/build/d3-queue.js:33:5)
    at module.exports (/home/pi/audiogram/server/status.js:7:6)
    at Layer.handle [as handle_request] (/home/pi/audiogram/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/audiogram/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/audiogram/node_modules/express/lib/router/route.js:112:3)`
