### ISSUE TITLE
can't install on MacOSX.  Fails @ node-gyp

### ISSUE THREAD

**Issue by willenglishiv** [nypublicradio/audiogram#45]
```sh
32684 verbose lifecycle canvas@1.4.0~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/wenglish/Sites/www/audiogram/node_modules/canvas/node_modules/.bin:/Users/wenglish/Sites/www/audiogram/node_modules/.bin:/usr/local/Cellar/node/6.3.1/bin:/Users/wenglish/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/brad/Dropbox/Working/vvv-provision-flipper:/Users/wenglish/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/opt/sm/bin:/opt/sm/pkg/active/bin:/opt/sm/pkg/active/sbin:/usr/local/heroku/bin:/Users/wenglish/dotfiles/misc:/Users/wenglish/dotfiles/bin:/Users/wenglish/.composer/vendor/bin:/Users/wenglish/go/bin
32685 verbose lifecycle canvas@1.4.0~install: CWD: /Users/wenglish/Sites/www/audiogram/node_modules/canvas
32686 silly lifecycle canvas@1.4.0~install: Args: [ '-c', 'node-gyp rebuild' ]
32687 silly lifecycle canvas@1.4.0~install: Returned: code: 1  signal: null
32688 info lifecycle canvas@1.4.0~install: Failed to exec install script
32689 verbose unlock done using /Users/wenglish/.npm/_locks/staging-ab6e0168211d3c6b.lock for /Users/wenglish/Sites/www/audiogram/node_modules/.staging
32690 silly rollbackFailedOptional Starting
32691 silly rollbackFailedOptional Finishing
32692 silly runTopLevelLifecycles Finishing
32693 silly install printInstalled
32694 verbose stack Error: canvas@1.4.0 install: `node-gyp rebuild`
32694 verbose stack Exit status 1
32694 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
32694 verbose stack     at emitTwo (events.js:106:13)
32694 verbose stack     at EventEmitter.emit (events.js:191:7)
32694 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
32694 verbose stack     at emitTwo (events.js:106:13)
32694 verbose stack     at ChildProcess.emit (events.js:191:7)
32694 verbose stack     at maybeClose (internal/child_process.js:852:16)
32694 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
32695 verbose pkgid canvas@1.4.0
32696 verbose cwd /Users/wenglish/Sites/www/audiogram
32697 error Darwin 14.5.0
32698 error argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "install"
32699 error node v6.3.1
32700 error npm  v3.10.7
32701 error code ELIFECYCLE
32702 error canvas@1.4.0 install: `node-gyp rebuild`
32702 error Exit status 1
32703 error Failed at the canvas@1.4.0 install script 'node-gyp rebuild'.
```

I noticed in the package.JSON that it's pointing to @chearon/node-canvas instead of the repo version.  Changing ```package.json``` over to the latest version of canvas will install the app itself, but produce another error (which I dont know if it's related or not)  here:

```sh

info: Listening on 8888
/Users/wenglish/Sites/www/audiogram/lib/register-fonts.js:8
    Canvas.registerFont(font.file, _.pick(font, "family", "weight", "style"));
           ^

TypeError: Canvas.registerFont is not a function
    at /Users/wenglish/Sites/www/audiogram/lib/register-fonts.js:8:12
    at Array.forEach (native)
    at Object.<anonymous> (/Users/wenglish/Sites/www/audiogram/lib/register-fonts.js:7:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
^C^
```

Lastly, I'm on OSX 10.10.5 Yosemite, node 6.3.1 and npm 3.10.7.   I tried this on a El Capitan OSX install, still did not work.  Any help would be appreciated!

**Comment by willenglishiv** [comment]
I got it working.

I had to do the following:

```brew install pango ffmpeg yasm lame cake libgroove```

That way all the dependencies don't fail, run ```npm install``` again.  Works after that 100%

**Comment by veltman** [comment]
Interesting - AFAIK you shouldn't need to install `yasm`, `lame`, or `cake`, but the other three are required.  More details here:

https://github.com/nypublicradio/audiogram/blob/master/INSTALL.md

It points to the `chearon` fork of `node-canvas` because font handling on the core branch is broken.
