### ISSUE TITLE
Waiting for other jobs to finish but they never do

### ISSUE THREAD

**Issue by xanxanxan** [nypublicradio/audiogram#91]
I use audiogram on my local machine. I started a job and it got stuck at the "Waiting for other jobs to finish, #1 in queue" stage. Since it didn’t move, I restarted it. Now "#2 in queue" and still no progress. Restarting audiogram doesn’t do any good.

My terminal output is the following:
```
troth@kakao:~/audiogram$ npm start

> audiogram@0.9.5 start /home/troth/audiogram
> npm run postinstall && bin/server


> audiogram@0.9.5 postinstall /home/troth/audiogram
> mkdir -p editor/js && browserify client/index.js > editor/js/bundle.js

info: Listening on 8888
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libgif.so.4: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/troth/audiogram/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
^C
troth@kakao:~/audiogram$ npm start

> audiogram@0.9.5 start /home/troth/audiogram
> npm run postinstall && bin/server


> audiogram@0.9.5 postinstall /home/troth/audiogram
> mkdir -p editor/js && browserify client/index.js > editor/js/bundle.js

info: Listening on 8888
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libgif.so.4: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/troth/audiogram/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by yitbosaz** [comment]
Following this thread, I'm having the exact same issue.

**Comment by ryanwellsdotcom** [comment]
I was able to resolve a similar error that suddenly started to receive one day by downgrading node/npm. 

1. If you installed node with brew, run 
`brew uninstall node`
`brew install node@6`
`brew link node@6` (you may have to force this. I also had to add this as a new PATH when prompted)

2. Then I ran `brew uninstall --ignore-dependencies pkg-config cairo pango libpng jpeg giflib ffmpeg`

Also, ensure canvas isn't installed outside of the project. I had it installed so ran `npm uninstall canvas` and `npm uninstall canvas -g`

As an aside, ensure you xCode is up-to-date and that you've opened it/accepted the license. I also ran `xcode-select --install`

3. REBOOT the machine at this point

4. run `brew install pkg-config cairo pango libpng jpeg giflib ffmpeg`

5. run `npm install node-gyp -g` (you may need to relink brew to node@6 again at this point for some reason)

6. Delete the node_modules directory from your local projec. CD to the project directory and run `npm install` then `npm start`

After spending two days on this, this resolved my issue. I think moving forward, the most stable way to run this is to dedicate a VM to it. I have other projects that require the latest NPM, so this fix is temporary.

**Comment by guahuanggeg** [comment]
@ryanwellsdotcom , I repeated the step and this seems not fix the issue.  Any further steps would you suggest?
